project:
  type: website
  output-dir: docs
  
website:
  title: "Chenglong Wang"
  page-footer: 
    right: "Copyright 2023, Chenglong Wang"
    background: light
  navbar:
   right:
      - href: index.qmd
        text: Home
      # - href: blog.qmd
      #   text: Blog
      - href: research.qmd
        text: Project
      - href: publication.qmd
        text: Publication
      - href: teaching.qmd
        text: Teaching
      - href: team.qmd
        text: Award & Service
      - href: contact.qmd
        text: Contact
      #- text: "More"
        #menu: 
         # - talks.qmd
          #- about.qmd
      # - icon: ResearchGate
      #   href: https://github.com/my_user_name
      # - icon: twitter
      #   href: https://twitter.com/my_user_name
      # - icon: google shcolar
      #   href: https://twitter.com/my_user_name
      # - icon: researchgate
      #   href: https://twitter.com/my_user_name
     
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

freeze: auto
