---
listing:
  type: default
  contents: posts
  #sort: "date desc"
  categories: False
---

### Presentation and talk

*WANG Chenglong*. "Comparative analysis of accessibility between general hospitals and specialized hospitals based on two-step floating catchment area method: a case of Shanghai". Presentation at Spatiotemporal Innovation Workshop, sponsored by Future Data Lab, Center for Geographical Analysis at Harvard University, Spatial Temporary Innovation Center. 2022.

*WANG Chenglong*. "How Subjective Economic Status Matters: The Reference-Group Effect on Migrants' Settlement Intention in Urban China". Presentation at 11th International Conference on Population Geographies, Tokyo, Japan. 2022.

*WANG Chenglong*. "Migration and Settlement in China: Patterns, Determinants and Motivation". Invited talk at The Max Planck Institute for Demographic Research, Germany. 2022.

*WANG Chenglong*. "Chinese Immigrants in Japan". Invited talk at Nanzan University, Japan. 2019.

*WANG Chenglong*, REN Yixin, JI Zichan. "Urban renewal in China's old community: a case of Jinsong North Community, Beijing". Presentation in Exchange Programme for Students and Teachers in Hong Kong, Macao and Mainland China 2019. Hosted by Peking University. 2019.

*WANG Chenglong*, ZHOU Wangyu, ZHOU Minhui, LI Piaoyan. "City on the Move". Presentation at 2018 BMW Next Mobility Youth Camp. Excellent Proposal Award. Organized by "BMW China Automotive Trading Ltd." and "The Chinese People Association for Friendship with Foreign Countries". 2018.

*WANG Chenglong*, SMITH Warren, BUTT Sidra, HOSSANEE Shaziah, OLADIIPO Funmilola, ROCKAR Ella. "Open Space in Sai Ying Pun, Hong Kong". Presentation at The Association of Commonwealth Universities Summer School. 2018.

*WANG Chenglong*. "Exploring the Mechanism of Border Effect on Urban Land Expansion: A Case Study of Beijing-Tianjin-Hebei Region in China." Presentation at Hong Kong Geography Day. 2018.
